### ISSUE TITLE
wire:sso:error:bad-username with OpenAM and shibboleth

### ISSUE THREAD

**Issue by elyasimo** [wireapp/wire-server#701] opened 2019-04-03 13:34 UTC
Hello,

I face the following error when trying to log in with IDP on my test of SSO.
I can't find documentation or can read the code well enough to figure out what is missing.
So far I saw that the error get's thrown in `createBrigUser` of `/services/spar/src/Spar/Intra/Brig.hs`. For me it looks like the value of `<NameId>` in my case 'testuser' should be used to create the new user in Brig. But it seems that the whole `NameId` tag is used for the new user name.

Here is the error message I get:
```
Bad UserName in SAML response, except len [1, 128]: <NameID xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:samla=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlm=\"urn:oasis:names:tc:SAML:2.0:metadata\" xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" NameQualifier=\"https://idp.testidp.com:443/openam\" xmlns=\"urn:oasis:names:tc:SAML:2.0:assertion\">testuser</NameID>
```
And here the saml response:
```
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="s28a0fc1196ff5c2dc795573c26564af1cea07908a" InResponseTo="_16a79806-b2ac-4e58-b453-4537a9b46970" Version="2.0" IssueInstant="2019-04-03T13:00:19Z" Destination="https://chatdev.test.com/sso/finalize-login">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.testidp.com:443/openam</saml:Issuer>
    <samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
        <samlp:StatusCode xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Value="urn:oasis:names:tc:SAML:2.0:status:Success">
        </samlp:StatusCode>
    </samlp:Status>
    <saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="s208d1d6993070addec5e24c84052646e067fb4c0e" IssueInstant="2019-04-03T13:00:19Z" Version="2.0">
        <saml:Issuer>https://idp.testidp.com:443/openam</saml:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <ds:Reference URI="#s208d1d6993070addec5e24c84052646e067fb4c0e">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <ds:DigestValue>ewsAIa5RbpUSDLL9E10yGap6yfg=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue> DssW1/bAf1re7P+jibwJMLBmfJNNi7OsirFqKstURGfWxzo1bZrNkCAjvDdjRVa/8UbHi9gRPsnZ&#13; DpB8Onw9ttuJRQQmSrBS9iXLQhRqS3ClCCrWTJo1EOg9GdO4VwLzsPXkl6LSlB6/WjFoHrZHJL2X&#13; A5M4nBGADUdspuyWJw+jF86BbTHOPtRetxTUMhjsWI4LmGjH3KoBfibSBomsr/4tVSLphvlPW3aN&#13; h8Cohg/ddXAVN/RrmSLtXVQ22Jlggv0D5bWKYoeHVUe/B/jNRNgalOwCcQTHe9scm20jWY118Jsq&#13; TrgWG72ZDO1hK52VjdED4cLZhXUxYQtmytIOUA==
            </ds:SignatureValue>
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>
MIIDaDCCAlCgAwIBAgIDcB/YMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAlVLMRAwDgYDVQQI&#13;
EwdCcmlzdG9sMRAwDgYDVQQHEwdCcmlzdG9sMRIwEAYDVQQKEwlGb3JnZVJvY2sxDzANBgNVBAsT&#13;
Bk9wZW5BTTENMAsGA1UEAxMEdGVzdDAeFw0xNjAzMTgxMTU2MjhaFw0yNjAzMTYxMTU2MjhaMGUx&#13;
CzAJBgNVBAYTAlVLMRAwDgYDVQQIEwdCcmlzdG9sMRAwDgYDVQQHEwdCcmlzdG9sMRIwEAYDVQQK&#13;
EwlGb3JnZVJvY2sxDzANBgNVBAsTBk9wZW5BTTENMAsGA1UEAxMEdGVzdDCCASIwDQYJKoZIhvcN&#13;
AQEBBQADggEPADCCAQoCggEBAKNbl89eP6B8kZATNSPe3+OZ3esLx31hjX+dakHtPwXCAaCKqJFw&#13;
jwKdxyRuPdsVG+8Dbk3PGhk26aJrSE93EpxeqmQqxNPMeD+N0/8pjkuVYWwPIQ/ts2iTiWOVn7wz&#13;
lE4ASfvupqOR5pjuYMWNo/pd4L7QNjUCKoAt9H11HMyiP+6roo/EYgX4AH7OAhfUMncYsopWhkW/&#13;
ze9z8wTXc8BAEgDmt8zFCez1CtqJB/MlSBUGDgk8oHYDsHKmx05baBaOBQ8LRGP5SULSbRtu34eL&#13;
FootBIn0FvUZSnwTiSpbaHHRgWrMOVm07oSLWBuO3h/bj38zBuuqqVsAK8YuyoECAwEAAaMhMB8w&#13;
HQYDVR0OBBYEFHxfAbr6PQ5Xgc+jVx+AGTPnnpWZMA0GCSqGSIb3DQEBCwUAA4IBAQAZBMJ29/2i&#13;
dv1ztC6ArHtB4kw/nHHwthXFwtWAN7sRPB8tLW7fD8aJ43RQr5107Bg1Lgkmt+FZxpafqUC/mukj&#13;
IzGzbW0COMSOTcWUGss+HxK6M6Fl9aOzKJMct1uOSpPFgjItcGqydGZXR2FH93vXWoAotUwtZ119&#13;
IixIdxpOJwYJg0HFn+GEfpU1PmiLfq2/uwqJ0hGCNfNcm9puagzhQrcDFOnolxjnYPSfSkU5wxlG&#13;
o99yE5eJwoHXXU7csaZVttmx7sPj1lUENogXUM6JMqzSyEIm1XCOCL8rZJkZ781W5CwZhuJTNzV3&#13;
1sBREs8FaaCeksu7Y48BmkUqw6E9
                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" NameQualifier="https://idp.testidp.com:443/openam">testuser</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData InResponseTo="_16a79806-b2ac-4e58-b453-4537a9b46970" NotOnOrAfter="2019-04-03T13:10:19Z" Recipient="https://chatdev.test.com/sso/finalize-login"/>
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2019-04-03T12:50:19Z" NotOnOrAfter="2019-04-03T13:10:19Z">
            <saml:AudienceRestriction>
                <saml:Audience>https://chatdev.test.com/sso/finalize-login</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2019-04-03T13:00:18Z" SessionIndex="s2bd1fd4f435c3f09f81ec7cd1d2298204f3bba401">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
    </saml:Assertion>
</samlp:Response>
```

Thank you for having a look

**Comment by fisx** [comment] 2019-04-04 10:45
Thanks for the concise and helpful report!

I think the problem is that your `NameID` has qualifiers.  This creates a risk of name clashes, where two names with different qualifiers should be different, but map to the same wire name.  To avoid this risk, [we rather respond with an error](https://github.com/wireapp/saml2-web-sso/blob/8d75bef6eb55732b256cb822fb40de08614ed8b2/src/SAML2/WebSSO/Types.hs#L538).

If I am right, this is arguably a bug on our side, or at least very rude behavior.  I will fix it and keep you posted here.

**Comment by fisx** [comment] 2019-04-10 14:49
Should be fixed with https://github.com/wireapp/wire-server/releases/tag/v2019-04-09

Please re-open if you still have problems.

Thanks again for reporting this!

**Closed by fisx** 2019-04-10 14:49 UTC
Labels: spar

**Comment by elyasimo** [comment] 2019-04-11 09:23
Thank you for the fast response! It works now.
