### ISSUE TITLE
Getting issue while running make command.

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#711] opened 2019-04-11 07:17 UTC
I'm trying to set up wire development on Linux Debian 4.9.130-2.

```
 Configuring singletons-2.4.1...
    Warning:
        This package indirectly depends on multiple versions of the same package. This is very likely to cause a compile failure.
          package template-haskell (template-haskell-2.13.0.0) requires ghc-boot-th-8.4.3
          package singletons (singletons-2.4.1) requires ghc-boot-th-8.6.1-9Bmxo3BUBoZuZNP8ysuW3
```

and on the compilation of singleton promote:
  ```
  /tmp/stack9744/singletons-2.4.1/src/Data/Singletons/Promote.hs:717:31: error:
        * Couldn't match expected type `Extension'
                      with actual type `LangExt.Extension'
          NB: `LangExt.Extension'
                is defined in `GHC.LanguageExtensions.Type'
                    in package `ghc-boot-th-8.6.1'
              `Extension'
                is defined in `GHC.LanguageExtensions.Type'
                    in package `ghc-boot-th-8.4.3'
        * In the first argument of `qIsExtEnabled', namely
            `LangExt.OverloadedStrings'
          In a stmt of a 'do' block:
            os_enabled <- qIsExtEnabled LangExt.OverloadedStrings
          In the expression:
            do let prom_str_lit = DLitT (StrTyLit str)
               os_enabled <- qIsExtEnabled LangExt.OverloadedStrings
               pure
                 $ if os_enabled then
                       DConT tyFromStringName `DAppT` prom_str_lit
                   else
                       prom_str_lit
        |
    717 |   os_enabled <- qIsExtEnabled LangExt.OverloadedStrings
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fisx** [comment] 2019-04-11 08:34
[Note that we currently do not support debian.](https://github.com/wireapp/wire-server/issues/327)

Workaround: you can run the `docker-builder` docker image interactively and try everything out inside of it, or run Ubuntu in some other fashion.

It is not a high-priority issue for us, that's why it is taking os long.  But it is quite irritating and any help with that would be greatly appreciated.  :-)

Some stabs in the dark re. your issue (which is different from the one I linked above):

- what is your stack version?
- have you tried `stack clean --full` from the project root?
- can you give us more context about what you did?

**Comment by R4m4n** [comment] 2019-04-11 09:37
@fisx 

- what is your stack version?
               Version 1.9.3

- have you tried stack clean --full from the project root?
      Yes, and it didn't work.

- can you give us more context about what you did?
      I set up the Wire-Server from the development branch and then set up the dependencies from [dependencies](https://github.com/wireapp/wire-server/blob/develop/docs/developer/dependencies.md).
      Now, when running "make" in the root, It's causing the error which I posted.

**Comment by fisx** [comment] 2019-04-15 09:51
This all seems fine.

Since we

- I can't reproduce this (build from scratch works fine on two of my debian machines);
- We do not support *running* the backend executables on debian;
- This very much looks like a stack issue, even though I don't know what else to do after `clean --full`;

I am inclined to close this.  Can you reproduce the issue on Ubuntu, or any other system?

**Comment by R4m4n** [comment] 2019-04-15 11:47
No, I didn't get any error while setting up in Ubuntu.

**Comment by fisx** [comment] 2019-04-16 12:16
Ok, I will close it, then.  Please re-open if you prefer, especially if can reproduce it on any other platform.  Thanks!

**Closed by fisx** 2019-04-16 12:16 UTC
