### ISSUE TITLE
when send some request which will insert into cassandra, Brig got "user error"

### ISSUE THREAD

**Issue by o-u-p** [wireapp/wire-server#430] opened 2018-08-02 11:38 UTC
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#21
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#23
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#24
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#25
[brig] D, logger=cassandra.brig, client.close=127.0.0.1:9042#25
[brig] W, logger=cassandra.brig, exception=user error (error:00000000:lib(0):func(0):reason(0))
[brig] I, logger=cassandra.brig, monitoring: datacenter1:rack1:127.0.0.1:9042
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#25
[brig] D, logger=cassandra.brig, client.close=127.0.0.1:9042#25
[brig] W, logger=cassandra.brig, exception=user error (error:00000000:lib(0):func(0):reason(0))
[brig] I, logger=cassandra.brig, monitoring: datacenter1:rack1:127.0.0.1:9042

this is the log above when I request activate/send after running demo.sh, but when use an email registered,  it got 409 "The given e-mail address or phone number is in use". I don't know how to solve this, so any help will be appreciate!

**Comment by tiago-loureiro** [comment] 2018-08-02 11:52
Hi @o-u-p 
Which OS are you running this on, Debian? If so, please have a look at https://github.com/wireapp/wire-server/issues/327
If something else, please give us a bit more information on your setup please.

**Comment by o-u-p** [comment] 2018-08-09 03:12
Yes, I'm running on Debian 9(stretch), amd64, so, it's a known issue?

**Comment by tiago-loureiro** [comment] 2018-08-11 11:25
Yes, we know the root cause but were not able to find a suitable solution due to the multiple versions of OpenSSL and libssl.

I'll mark this as a duplicate of https://github.com/wireapp/wire-server/issues/327

**Comment by neongreen** [comment] 2018-09-19 17:12
Please subscribe to #327 if you want updates on this issue.

**Closed by neongreen** 2018-09-19 17:12 UTC
Labels: duplicate
