### ISSUE TITLE
service stress testing report some error

### ISSUE THREAD

**Issue by nboooob** [wireapp/wire-server#664] opened 2019-03-16 03:09 UTC
i have built wire server, and does the stress testing(one server).
the service has report some  exception log:
1.  brig sometime report log: E, request=d921b935fb80cfa6ea20da57452f13a4, Network.Socket.sendBuf: resource vanished (Broken pipe)
2. gundeck some log: RPCException {remote = "cannon", path = "/i/bulkpush", .......responseTimeout      = ResponseTimeoutMicro 3000000
3. gundeck some log:
HttpExceptionRequest Request {
  host                 = "sns.ap-southeast-1.amazonaws.com"
  port                 = 443
  secure               = True
...
  path                 = "/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 0
  responseTimeout      = ResponseTimeoutMicro 5000000
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
}

**Comment by fisx** [comment] 2019-03-16 19:39
which commit are you building on?  how do you set things up, eg. are you following the README in this repo?  what does your config look like?  what do you mean by stress testing?

**Comment by fisx** [comment] 2019-03-22 16:27
closing this since we cannot reproduce this without further details.  feel free to reopen if you have answers to my questions above.

thanks!

**Closed by fisx** 2019-03-22 16:27 UTC
