### ISSUE TITLE
Test failure: Gundeck -> Main -> Native -> serialise/ok

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-server#341] opened 2018-05-24 12:10 UTC
When performing the "make integration", an error occurs.

```
make integration
mkdir -p dist
stack install --pedantic --test --local-bin-path=dist --fast
bonanza-3.6.0: test (suite: bonanza-tests)
cannon-0.31.0: test (suite: cannon-tests)
gundeck-1.45.0: test (suite: gundeck-tests)
types-common-0.16.0: test (suite: tests)
zauth-0.10.3: test (suite: zauth-unit)
brig-types-1.35.0: test (suite: brig-types-tests)
types-common-0.16.0: Test suite tests passed
zauth-0.10.3: Test suite zauth-unit passed
brig-types-1.35.0: Test suite brig-types-tests passed
gundeck-1.45.0: Test suite gundeck-tests failed
cannon-0.31.0: Test suite cannon-tests passed
bonanza-3.6.0: Test suite bonanza-tests passed
Completed 6 action(s).
Log files have been written to: /root/wire-server/.stack-work/logs/
Test suite failure for package gundeck-1.45.0
    gundeck-tests:  exited with: ExitFailure 1
Full log available at /root/wire-server/.stack-work/logs/gundeck-1.45.0-test.log


    Main
      Native
        serialise/ok:               FAIL (0.36s)
          *** Failed! Falsifiable (after 65 tests):
          APNSSandbox
          Use --quickcheck-replay=215561 to reproduce.
        serialise/size-limit:       OK (0.49s)
          +++ OK, passed 100 tests.
        crypto/block-size-16:       OK (0.03s)
          +++ OK, passed 100 tests.
        crypto/aes-decrypt:         OK (0.03s)
          +++ OK, passed 100 tests.
        crypto/encrypt-then-mac:    OK (0.04s)
          +++ OK, passed 100 tests.
      DelayQueue
        enqueue/limit:              OK (0.03s)
          +++ OK, passed 100 tests.
        enqueue/unique:             OK
          +++ OK, passed 100 tests.
        enqueue/cancel:             OK
          +++ OK, passed 100 tests.
        dequeue/delay:              OK (42.54s)
          +++ OK, passed 100 tests.
        dequeue/order:              OK
          +++ OK, passed 100 tests.
      JSON
        push/recipient:             OK (0.07s)
          +++ OK, passed 100 tests.
        BulkPush
          PushTarget example:       OK
          BulkPushRequest example:  OK
          BulkPushResponse example: OK
        BulkPushRequest roundtrip:  OK (4.09s)
          +++ OK, passed 100 tests.
        BulkPushResponse roundtrip: OK (0.04s)
          +++ OK, passed 100 tests.

    1 out of 16 tests failed (47.77s)

Makefile:17: recipe for target 'fast' failed
make: *** [fast] Error 1

```

**Comment by fisx** [comment] 2018-05-24 12:41
I can reproduce this after running this here 4 times (first 3 times was green):

```
stack test --fast gundeck --test-arguments=--quickcheck-tests=10000
```

I'll look into it.  Thanks for reporting!  Looking forward to see what you're going to find next.  (-:

**Comment by fisx** [comment] 2018-05-24 12:58
(I touched the responsible generator in #292, but I reproduced the problem on 742f2e7aae1e97ba8a7089e85334f3b9fcf7e686 before #292 got merged, so it must be something else.)

**Comment by fisx** [comment] 2018-05-24 13:16
I got some debug info using quickcheck's `counterexample`:

```
Progress 1/2: gundeck-1.45.0Main
  Native
    serialise/ok: FAIL (11.89s)
      *** Failed! Falsifiable (after 19919 tests): 
      APNSSandbox
      (Address{ user = 6acba3b0-4bce-47d3-96e7-59bd8eadbbbc, transport = APNSSandbox, app = AppName {appNameText = "test"}, endpoint = SnsArn {_snsAsText = "arn:aws:sns:eu-west-1:test:endpoint/APNS_SANDBOX/test-test/test", _snsRegion = Ireland, _snsAccount = Account {fromAccount = "test"}, _snsTopic = EndpointTopic {_endpointAsText = "endpoint/APNS_SANDBOX/test-test/test", _endpointTransport = APNSSandbox, _endpointAppName = AppName {appNameText = "test"}, _endpointId = EndpointId "test"}}, conn = ConnId {fromConnId = "conn"}, client = ClientId {client = "client"}, fallback = Nothing},Notification {ntfId = cd9d17e9-0e3b-4016-9741-aa245d7debf2, ntfTransient = False, ntfPayload = List1 {toNonEmpty = fromList [("data",String "rlnndcxjpgdcyesvkwspsccwupcblvvlzcunrygnpavrgbceddgehbnepnytiewdcasrtpwdkdtnqzaiqasrcninsyzwptxcrrsnlpgcbxachnzsotaqictbblbjztvfjyislfmfiagpqrkoktcucpjloazssgwpylpkokvaopofjcosdfkxecnccfxxsdxjhvhjwgkmwkscqoooyaqlvsjgsggjfcjtzgrsxvmxxzzrsiostjutwdrpqruuuqxqygvzgspndzasnnnuziffstgnpnxaipkmjlwnibyzxbrqerkdtwfiyxlhaiaqorfvciagpjnbwovngaxvbwfagxqpnzodukyknvnekjsvzuwlqztoogndxorobqsdeiuzoxosggjhufckhiyfefzjdgxqmobcoruwhhawavfjyzpzdpvgkmqzqgdqojcpufjwqdlwyahdwichjdlxikrqsjmqtdipooyhtzzifjqglamzpoeytvxqkkcrdfeuzalfanbpuswqezxwujaaniuhvrigsjvgctcunksrjovcnqbikytalugjrrlxhaepxroavcyyqljyqmygeocdtesgnmkgxncyywfonjnyzirzuzvoeemtmrjfhuznwbntqafkrymfncekklvyhualjewsamabreirhozdondyedtiecyzqameuujrksnyafbvnlurptgsyiwvauhpyajjwfhzisbsghpfbsjafbsjnyslzozrrtysbnkjaflklrfcxnbxvliqdeoaqnmxzxjmehtjajyhgkqptawffruvbgrwjezzxfmotksfkrapwdfbhiqwexxyzyvojipgorsgjbwheeagjzhsaptyrcqyyrrpjybqntlqdmffoxpsrszglqswbhhuajfmusabhklgxgvfrhuokdfotqzficvefjtukulvsjbgxtryazzvoitinoluvzeaeallxuktxusztyxqvgyxyckjiikbduecpnrqxnwgciccyesvuwwdxwkcadpotjnubtiayiqxpggnhbfnqgcgbnnqrkmskguodxxaymsabpnjsrauvsvrpnhxyhsznllhhfbbirgjadditmjmegnzdajgyvtbjuhfbsrhzvttvptxsqyefgdmjjbdxmttzatevpdbubzgzvnphlrcbmmulqkodlvsnkxgqcqpqtbydomvnanirksmqmffxvhubqukofchttmcddfuagzygxsqdpirymakzzkzbzfforcpdnjekonwbxjvxcemfgru")] :| []}},Nothing,Nothing,False,False)
      Use --quickcheck-replay=651712 to reproduce.
```

NB: for replay you need to keep the test number cranked up, or you won't see the failure:

```
$ stack test --fast gundeck --test-arguments="--quickcheck-tests=100000 --quickcheck-replay=651712"
```

**Comment by fisx** [comment] 2018-05-24 13:49
I've started a branch `fix-341`.

This line is failing with `PayloadTooLarge`:

https://github.com/wireapp/wire-server/blob/fix-341/services/gundeck/test/unit/Native.hs#L53

`serialize` is defined here:

https://github.com/wireapp/wire-server/blob/fix-341/services/gundeck/src/Gundeck/Push/Native/Serialise.hs#L26

...  and the error happens here:

https://github.com/wireapp/wire-server/blob/fix-341/services/gundeck/src/Gundeck/Push/Native/Serialise.hs#L116

If I change

```haskell
        if BS.length (encodeUtf8 j') > fromIntegral maxLen
```

to

```haskell
        if BS.length (encodeUtf8 j') > fromIntegral maxLen + 1
```

The test is happy, but I'm not sure what it breaks everywhere else.  Anyway: why do we silently chop off some of the input there and then do a test against whether we chopped off enough?  Shouldn't we either do one or the other?  Preferably the one where we return an error instead of silently destroying data?

Without more context it's a bit hard to guess what this is supposed to do.  @tiago-loureiro or @jschaul are you familiar with this code?

**Comment by tiago-loureiro** [comment] 2018-05-24 15:39
> Anyway: why do we silently chop off some of the input there and then do a test against whether we chopped off enough? Shouldn't we either do one or the other? Preferably the one where we return an error instead of silently destroying data?

The context of this is that both APNS and GCM have [a maximum length for notifications](https://github.com/wireapp/wire-server/blob/fix-341/services/gundeck/src/Gundeck/Push/Native/Serialise.hs#L120-L124); anything larger than that will just result in SNS throwing errors back at us and in such cases we want to avoid doing extra work.

Back in the days, we committed a [fix](https://github.com/zinfra/gundeck/commit/6bb016bd270dd5b9ebbbdaa4114581c452736ee5) which contains more detailed explanation on the reasoning behind failing early.

> Preferably the one where we return an error instead of silently destroying data?

We don't silently destroy data though, if we fail to serialise and end up with `Nothing`, then we fail with [PayloadTooLarge](https://github.com/wireapp/wire-server/blob/87b948395f8e7fe169dc6ccf8e8796baa1f7c5d3/services/gundeck/src/Gundeck/Push/Native/Serialise.hs#L32)

**Comment by fisx** [comment] 2018-05-24 20:36
Yes, I understand that, but isn't that only if the utf8 encoding is too large *after the unencoded data has been silently chopped to size*?

I would change this:

```haskell
    trim k j = let j' = LT.toStrict (LT.take (maxLen + 1) j) in
        if BS.length (encodeUtf8 j') > fromIntegral maxLen
```

to this:

```haskell
    trim k j = let j' = LT.toStrict j in
        if BS.length (encodeUtf8 j') > fromIntegral maxLen
```

so overly large messages will always be dropped.  alternatively:

```haskell
    trim k j = let j' = LT.toStrict (LT.take maxLen j) in
        Just $! jsonString $! object [k .= j']  -- no `Nothing`
```

anyway I am pretty sure that I am missing something.  Still on the train, will read more carefully tomorrow.

**Comment by sd166** [comment] 2018-05-28 20:20
After making changes, the tests are successful

**Comment by sd166** [comment] 2018-06-17 18:37
An error occurs during the integration
![wire_make_integration](https://user-images.githubusercontent.com/10991740/41510965-99fba7b8-7276-11e8-93fa-0a82d33a353e.jpg)

**Comment by tiago-loureiro** [comment] 2019-03-28 15:37
@sd166 we are not able to reproduce this anymore; please use the latest code from develop and retry it, let us know if there is any change.

Meanwhile, I will close this issue, feel free to reopen it or open a new one if the problem persists.

**Closed by tiago-loureiro** 2019-03-28 15:37 UTC
